In [1]:
from __future__ import print_function
import torch

x=torch.empty(5,3)
print(x)

tensor([[7.7491e+26, 3.0357e+32, 6.3828e+28],
        [1.4603e-19, 1.8617e+25, 1.6212e-19],
        [1.8617e+25, 7.9438e+08, 3.2604e-12],
        [7.4086e+28, 1.9838e+29, 4.3218e+27],
        [4.7423e+30, 6.3828e+28, 1.4603e-19]])


In [2]:
x=torch.rand(5,3)
print(x)

tensor([[0.2599, 0.0157, 0.2333],
        [0.8218, 0.7330, 0.0212],
        [0.4979, 0.2321, 0.8223],
        [0.4221, 0.7680, 0.2213],
        [0.9190, 0.5236, 0.4119]])


In [3]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x= torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5789,  0.2638,  0.9572],
        [ 1.0371, -1.5822,  0.4711],
        [-0.2604,  0.4447,  0.2057],
        [-0.6498,  1.0858, -1.9897],
        [ 1.4789, -0.7964,  0.8544]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y=torch.rand(5,3)
print(x+y)


tensor([[-0.5477,  1.0283,  1.1727],
        [ 1.3741, -0.6400,  1.4167],
        [-0.0211,  0.4450,  0.8568],
        [-0.4035,  1.6114, -1.1420],
        [ 2.0473, -0.6160,  1.0149]])


In [8]:
print(torch.add(x,y))

tensor([[-0.5477,  1.0283,  1.1727],
        [ 1.3741, -0.6400,  1.4167],
        [-0.0211,  0.4450,  0.8568],
        [-0.4035,  1.6114, -1.1420],
        [ 2.0473, -0.6160,  1.0149]])


In [9]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.5477,  1.0283,  1.1727],
        [ 1.3741, -0.6400,  1.4167],
        [-0.0211,  0.4450,  0.8568],
        [-0.4035,  1.6114, -1.1420],
        [ 2.0473, -0.6160,  1.0149]])


In [10]:
y.add_(x)
print(y)

tensor([[-0.5477,  1.0283,  1.1727],
        [ 1.3741, -0.6400,  1.4167],
        [-0.0211,  0.4450,  0.8568],
        [-0.4035,  1.6114, -1.1420],
        [ 2.0473, -0.6160,  1.0149]])


In [11]:
print(y[:,1])

tensor([ 1.0283, -0.6400,  0.4450,  1.6114, -0.6160])


In [12]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x)
print(y)
print(z)

tensor([[-1.1924, -0.5738,  0.3614,  0.8682],
        [-1.3508, -0.4923, -0.2647, -1.7420],
        [ 1.3995,  1.6936,  0.7206, -1.1469],
        [-1.3670, -2.0721, -0.6076, -0.5069]])
tensor([-1.1924, -0.5738,  0.3614,  0.8682, -1.3508, -0.4923, -0.2647, -1.7420,
         1.3995,  1.6936,  0.7206, -1.1469, -1.3670, -2.0721, -0.6076, -0.5069])
tensor([[-1.1924, -0.5738,  0.3614,  0.8682, -1.3508, -0.4923, -0.2647, -1.7420],
        [ 1.3995,  1.6936,  0.7206, -1.1469, -1.3670, -2.0721, -0.6076, -0.5069]])


In [13]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([1.4110])
1.4109607934951782


In [14]:
a = torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
import numpy as np
a = np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
torch.cuda.is_available()

True

In [17]:
device=torch.device("cuda")


In [18]:
b.to(device)

tensor([2., 2., 2., 2., 2.], device='cuda:0', dtype=torch.float64)

In [19]:
torch.__version__

'1.2.0'

In [3]:
import torch
x=torch.ones(5,3,dtype=torch.double)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu"), torch.double)
    

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64) torch.float64


In [5]:
import torch
x=torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
z = y*y *3
out = z.mean()

In [8]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2,2)
a=((a*3)/(a*1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
print(y.grad)

None


In [12]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [16]:
x = torch.randn(3, requires_grad=True)
y=x*2
print(y)
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([1.2944, 1.0760, 0.7606], grad_fn=<MulBackward0>)
tensor([1325.4429, 1101.8040,  778.8585], grad_fn=<MulBackward0>)


In [17]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [20]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [53]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5) #16个卷积核对所有6个feature map做运算 然后加和在一起变成一个feature map
        self.fc1 = nn.Linear(16*5*5, 120)#5*5需要自己算出来
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    def num_flat_features(self, x):
        size = x.size()[1:]#不包括第一个到最后
        num_features=1
        for s in size:
            num_features *= s
        return num_features
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x= F.max_pool2d(F.relu(self.conv2(x)), 2)
        x= x.view(-1, self.num_flat_features(x))#展开摊平 -1表示不确定 不确定batchsize是多少 计算一下有多少个格子 把后面的全部摊开
        x= F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
net = Net()
print(net)
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [29]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


In [30]:
print(params)

[Parameter containing:
tensor([[[[-0.1528,  0.0072, -0.1336,  0.0302,  0.0958],
          [ 0.1780, -0.1294,  0.0791, -0.0780, -0.1337],
          [-0.1476,  0.1872, -0.1152,  0.1254, -0.1552],
          [ 0.1984,  0.1794,  0.1140, -0.0054, -0.0791],
          [ 0.1913,  0.1470,  0.0819,  0.0621, -0.0477]]],


        [[[ 0.1032,  0.0481, -0.0632,  0.1331, -0.1443],
          [-0.1839, -0.0194,  0.0055,  0.1306,  0.0307],
          [-0.1945,  0.1868,  0.0731,  0.1456, -0.0952],
          [ 0.1466,  0.1590,  0.1843,  0.1262, -0.1278],
          [ 0.1427,  0.1261,  0.0731,  0.1042, -0.1166]]],


        [[[-0.1798,  0.1040,  0.1953,  0.0726,  0.0955],
          [ 0.1368, -0.0829, -0.1356,  0.0056, -0.0124],
          [-0.1527,  0.0589, -0.0701,  0.1427, -0.1957],
          [-0.0526, -0.1015, -0.0073,  0.0582,  0.1530],
          [ 0.0544, -0.0348,  0.0417, -0.0312, -0.0080]]],


        [[[-0.0552, -0.0558, -0.1516,  0.0938,  0.0905],
          [-0.0145,  0.0240, -0.1131, -0.1139,  0.082

In [48]:
print(params[0].size()) # 5*5 每个通道一个 5*5*6  

torch.Size([10])


In [60]:
print(params[1].size())#bias也是一层 relu没有层

torch.Size([6])


In [54]:
input= torch.randn(1,1,32,32) #个数 通道数 高 宽
out = net(input)
print(out)
net.zero_grad()
out.backward(torch.randn(1,10))

tensor([[-0.0767, -0.1821,  0.1309, -0.0185,  0.1704, -0.1361,  0.0194, -0.0455,
          0.0074,  0.0348]], grad_fn=<AddmmBackward>)


In [62]:
output = net(input)
print(output)
target = torch.randn(10)
print(target)
target = target.view(1,-1)#在外面套一层 保证是batch
print(target)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor([[-0.0767, -0.1821,  0.1309, -0.0185,  0.1704, -0.1361,  0.0194, -0.0455,
          0.0074,  0.0348]], grad_fn=<AddmmBackward>)
tensor([ 0.8802, -2.8250,  2.1503,  0.5147, -0.7027,  0.1272,  0.4115, -0.6533,
         0.4705,  1.9512])
tensor([[ 0.8802, -2.8250,  2.1503,  0.5147, -0.7027,  0.1272,  0.4115, -0.6533,
          0.4705,  1.9512]])
tensor(1.7504, grad_fn=<MseLossBackward>)


In [69]:
print(loss.grad_fn)#MSELoss
print(loss.grad_fn.next_functions)
print(loss.grad_fn.next_functions[0][0]) #Linear
print(loss.grad_fn.next_functions[0][0].next_functions)
print(loss.grad_fn.next_functions[0][0].next_functions[0][0]) # Relu
print(output.grad_fn)#Linear
print(output.grad_fn.next_functions)

((<AddmmBackward object at 0x7f55c667f748>, 0),)
((<AccumulateGrad object at 0x7f55c667f748>, 0), (<ReluBackward0 object at 0x7f55c667f6d8>, 0), (<TBackward object at 0x7f55c667f7b8>, 0))
((<AccumulateGrad object at 0x7f55c667f7b8>, 0), (<ReluBackward0 object at 0x7f55c667f6d8>, 0), (<TBackward object at 0x7f55c667f7f0>, 0))


In [71]:
print(output.grad_fn)  
print(net.conv1.bias.grad_fn)  
    

None


In [73]:
net.zero_grad()
print(net.conv1.bias.grad)
loss.backward()
print(net.conv1.bias.grad)

tensor([0., 0., 0., 0., 0., 0.])
tensor([-0.0249, -0.0157,  0.0027, -0.0168, -0.0078, -0.0057])


In [74]:
print(net.parameters())

<generator object Module.parameters at 0x7f56c06bc480>


In [78]:
print(list(net.parameters())[0].grad.data)

tensor([[[[ 0.0119, -0.0171, -0.0060, -0.0098, -0.0047],
          [-0.0289, -0.0270,  0.0087, -0.0137,  0.0255],
          [ 0.0058,  0.0156,  0.0317,  0.0046, -0.0329],
          [ 0.0009, -0.0026,  0.0279, -0.0223,  0.0232],
          [-0.0056,  0.0398,  0.0149, -0.0315,  0.0149]]],


        [[[ 0.0377,  0.0276,  0.0058,  0.0016,  0.0282],
          [ 0.0138, -0.0043,  0.0081,  0.0008, -0.0045],
          [ 0.0048, -0.0197, -0.0066,  0.0175,  0.0224],
          [-0.0087, -0.0048,  0.0078, -0.0277, -0.0019],
          [ 0.0280, -0.0089,  0.0315, -0.0054,  0.0261]]],


        [[[-0.0016,  0.0159, -0.0120, -0.0249, -0.0332],
          [ 0.0115,  0.0204, -0.0150,  0.0028,  0.0152],
          [-0.0139,  0.0121, -0.0100, -0.0162,  0.0043],
          [-0.0059, -0.0193,  0.0124,  0.0101, -0.0052],
          [ 0.0111,  0.0039, -0.0013, -0.0160,  0.0119]]],


        [[[-0.0315,  0.0119,  0.0017,  0.0247,  0.0111],
          [-0.0203,  0.0206, -0.0050, -0.0266,  0.0354],
          [ 0.0155,

In [79]:
print(output)#para 才有梯度 中间的计算才有计算图

None


In [80]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.zero_grad()
output=net(input)
loss = criterion(output, target)
loss.backward()#计算梯度
optimizer.step()#更新参数

In [84]:
print(torch.squeeze(torch.rand(1,4)))
print(torch.squeeze(torch.rand(4,1)))

tensor([0.2625, 0.9698, 0.2917, 0.8740])
tensor([0.0252, 0.6980, 0.9098, 0.3081])


In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
net.to(device)


In [85]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader

input_size = 5
output_size = 2
batch_size = 30
data_size=100 #100条训练数据 每条训练数据里有5个数
device = torch.device("cuda: 0 " if torch.cuda.is_available() else "cpu")



In [88]:
class RandomDataset(Dataset):
    def __init__(self,size, length):
        self.len = length
        self.data = torch.randn(length, size)
    
    def __getitem__(self,index):
        return self.data[index]
    
    def __len__(self):
        return self.len
rand_loader =DataLoader(dataset=RandomDataset(input_size, data_size), batch_size=batch_size, shuffle=True) 

In [96]:
class Model(nn.Module):
    def __init__(self, input_size, output_size):#初始化函数
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)
    
    def forward(self, input):
        output=self.fc(input)
        print("\tIn Model: input size", input.size(), "output size", output.size())
        
        return output

        

In [97]:
model = Model(input_size, output_size)
if torch.cuda.device_count() >1:
    print("Let's use", torch.cuda.device_count(), "GPUs")
    model=nn.DataParallel(model)
model.to(device)


Let's use 8 GPUs


DataParallel(
  (module): Model(
    (fc): Linear(in_features=5, out_features=2, bias=True)
  )
)

In [98]:
for data in rand_loader:
    input=data.to(device)
    output=model(input)
    print("Outside: input size", input.size(),
         "output_size", output.size())

	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([2, 5]) output size torch.Size([2, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
	In Model: input size	In Model: input size torch.Size([4, 5]) 	In Model: input size torch.Size([4, 5]) output size torch.Size([4, 2])
ou

In [2]:
from __future__ import print_function,division
import os
import torch
import pandas as pd
from skimage import io,transform
import numpy as np
import matplotlib.pylot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils

import warnings
warnings.filterwarnings("ignore")

plt.ion()


ModuleNotFoundError: No module named 'skimage'